@startuml 訪問者システムドメインモデル図
skinparam componentStyle rectangle

' 訪問者システムのドメインモデル

[訪問者システム] o-- [訪問者]
[訪問者システム] o-- [Webページ]
[訪問者] o-- [ユーザーID]
[訪問者] o-- [パスワード]
[訪問者] o-- [名前]
[訪問者] o-- [学校名]
[訪問者] o-- [所属名]
[訪問者] o-- [メールアドレス]
[訪問者] o-- [電話番号]
[訪問者] o-- [年齢]

[訪問者] ..> [Webページ] : 閲覧

@enduml