@startuml
left to right direction

actor 訪問者

rectangle 訪問者システム {
  usecase "情報を登録する" as UC1
  usecase "情報を参照する" as UC2
  usecase "情報を変更する" as UC3
  usecase "情報を削除する" as UC4
}

訪問者 --> UC1
訪問者 --> UC2
訪問者 --> UC3
訪問者 --> UC4

@enduml