@startuml 大原情報科学大学・図書館システムドメインモデル図
skinparam componentStyle rectangle
[会員] o-- [会員番号]
[会員] o-- [借りている図書]
[会員] o-- [メールアドレス]
[会員] <|-- [学生]
[会員] <|-- [教職員]
[会員] o-- [メールアドレス]

[学生] o-- [学生証]
[学生] o-- [学生番号]

[教職員] o-- [職員証]
[教職員] o-- [職員番号]

[会員番号] <|-- [学生番号]
[会員番号] <|-- [職員番号]

[貸出情報] o-- [図書]
[貸出情報] o-- [貸出日]
[貸出情報] o-- [返却日]
[貸出情報] o-- [会員]

[図書] o-- [管理番号]
[図書] o-- [書名]
[図書] o-- [著者]
[図書] o-- [出版社]
[図書] o-- [ISBN]
[図書] <|-- [書籍]
[図書] <|-- [雑誌]

@enduml